name: Generate Hulk Video

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y ffmpeg
        pip install requests moviepy==1.0.3 Pillow python-dotenv imageio-ffmpeg

    - name: Run Script
      env:
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: python main.py

    - name: Upload Video Artifact
      uses: actions/upload-artifact@v4 # FIXED: v3 se v4 kar diya
      with:
        name: hulk-video
        path: hulk_bot_final.mp4
